/**
 * \file Ifx_Types.h
 * \brief This files defines all types used by the IFX HAL and libraries
 *
 * \version iLLD_1_20_0
 * \copyright Copyright (c) 2024 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef IFX_TYPES_H
#define IFX_TYPES_H 1

/* ============= BASIC TYPE DEFINITIONS FOR TDD ============= */
/* These replace Platform_Types.h which has compiler dependencies */
typedef unsigned char       uint8;
typedef unsigned short      uint16;
typedef unsigned int        uint32;
typedef unsigned long long  uint64;
typedef signed char         sint8;
typedef signed short        sint16;
typedef signed int          sint32;
typedef signed long long    sint64;
typedef float               float32;
typedef double              float64;
typedef unsigned char       boolean;

#ifndef TRUE
#define TRUE  1
#endif
#ifndef FALSE
#define FALSE 0
#endif
#ifndef NULL
#define NULL ((void*)0)
#endif

/* Fractional types (for DSP operations) */
typedef sint16              fract;
typedef sint8               sfract;

/* ============= END BASIC TYPE DEFINITIONS ============= */


/******************************************************************************/
/* mapping compiler specific keywords */
/*******************************************************************************
**                      Global Data Types                                     **
**                      (Types not defined by AUTOSAR)                        **
*******************************************************************************/
typedef const char        *pchar;                           /**< \brief const char pointer                               */
typedef void              *pvoid;                           /**< \brief void pointer                                     */
typedef volatile void     *vvoid;                           /**< \brief volatile void pointer                            */
typedef void              (*voidfuncvoid) (void);           /**< \brief void pointer which takes void argument           */

typedef struct
{
    float32 real;               /**< \brief Real part */
    float32 imag;               /**< \brief Imaginary part */
} cfloat32;

typedef struct
{
    sint32 real;				/**< \brief Real part */
    sint32 imag;				/**< \brief Imaginary part */
} csint32;

typedef struct
{
    sint16 real;				/**< \brief Real part */
    sint16 imag;				/**< \brief Imaginary part */
} csint16;

typedef sint64             Ifx_TickTime;    /**< \brief Time in ticks */
#define TIME_INFINITE ((Ifx_TickTime)0x7FFFFFFFFFFFFFFFLL)
#define TIME_NULL     ((Ifx_TickTime)0x0000000000000000LL)

#define IFX_ONES          (0xFFFFFFFFFFFFFFFFU)
#define IFX_ZEROS         (0x0000000000000000U)


#if CFG_LONG_SIZE_T
#define IFX_SIZET_MAX (0x7FFFFFFFL)
typedef sint32 Ifx_SizeT;                       /**< \brief Type used for data stream size */
#else
#define IFX_SIZET_MAX (0x7FFF)
typedef sint16 Ifx_SizeT;                       /**< \brief Type used for data stream size */
#endif

/** \brief Circular buffer definition. */
typedef struct
{
    void  *base;                   /**< \brief buffer base address */
    uint16 index;                  /**< \brief buffer current index */
    uint16 length;                 /**< \brief buffer length*/
} Ifx_CircularBuffer;

typedef uint16 Ifx_Priority;       /**< \brief Used in interrupt service priorities */
typedef uint32 Ifx_TimerValue;     /**< \brief Used in timer values */
typedef sint32 Ifx_SignedTimerVal; /**< \brief Used in signed timer values */

typedef pvoid  Ifx_AddressValue;   /**< \brief Used in address values */

/** \brief Signal active state definition. */
typedef enum
{
    Ifx_ActiveState_low  = 0,       /**< \brief The signal is low active */
    Ifx_ActiveState_high = 1        /**< \brief The signal is high active */
} Ifx_ActiveState;

/**
 * Defines the PWM modes
 *
 * The 1st member shall start with value 0, and the next members value shall be the previous member +1
 * pwmMode_off shall be the member with the higher index
 * \note enum order and values should not be modified, except Ifx_Pwm_Mode_init and Ifx_Pwm_Mode_count
 */
typedef enum
{
    Ifx_Pwm_Mode_centerAligned         = 0, /**< \brief Center aligned mode */
    Ifx_Pwm_Mode_centerAlignedInverted = 1, /**< \brief Center aligned inverted aligned mode */
    Ifx_Pwm_Mode_leftAligned           = 2, /**< \brief Left aligned mode. The PWM period starts with a rising edge */
    Ifx_Pwm_Mode_rightAligned          = 3, /**< \brief Right aligned mode. The PWM period starts with a falling edge*/
    Ifx_Pwm_Mode_off                   = 4, /**< \brief All switch open */
    Ifx_Pwm_Mode_init                  = 5, /**< \brief Initialisation mode, do not use at run time */
    Ifx_Pwm_Mode_count                      /**< \brief Number of defined modes */
} Ifx_Pwm_Mode;

/** \brief Module address and index map */
typedef struct
{
    volatile void *module;      /**< \brief Module address */
    sint32         index;       /**< \brief Module index */
} IfxModule_IndexMap;




typedef struct
{
    fract real;				/**< \brief Real part */
    fract imag;				/**< \brief Imaginary part */
} cfract;

typedef struct
{
    sfract real;				/**< \brief Real part */
    sfract imag;				/**< \brief Imaginary part */
} csfract;

#define IFX_PI                  (3.1415926535897932384626433832795f)
#define IFX_TWO_OVER_PI         (2.0 / IFX_PI)
#define IFX_ONE_OVER_TWO_PI     (1.0f / (2.0f * IFX_PI))
#define IFX_ONE_OVER_SQRT_THREE (0.57735026918962576450914878050196f)
#define IFX_SQRT_TWO            (1.4142135623730950488016887242097f)
#define IFX_SQRT_THREE          (1.7320508075688772935274463415059f)
#define IFX_UNUSED_PARAMETER(x) if(x){}             /**< \brief Added to handle warning resulting from cases where one/multiple function argument(s) is/are not used(but function signature maintained for legacy purposes). Another use case being usage of intrinsics wherein the compiler ignores it and copy pastes the statements using intrinsics directly to the object file and hence usage of arguments isn't visible to it.(eg: __mfcr() etc) */ 


/* ===== TDD MOCK MODULE INSTANCES ===== */

/* ===== TDD STUB TYPE DEFINITIONS ===== */
/* These stub types allow TDD compilation without full iLLD SFR headers.
   They include members commonly used by production code for 3-phase inverter PWM.
   
   IMPORTANT: Use #ifndef guards to avoid conflicts with real iLLD definitions!
   Real iLLD Ifx_Types.h already defines: Ifx_ActiveState, Ifx_Pwm_Mode, etc.
   We only add types that are MISSING from real iLLD. */

/* SFR Module stub types - these are NOT in Ifx_Types.h, they're in SFR headers */
#ifndef IFX_GTM_DEFINED
typedef struct { volatile uint32 dummy; } Ifx_GTM;
#define IFX_GTM_DEFINED
#endif

#ifndef IFX_P_DEFINED
typedef struct { volatile uint32 dummy; } Ifx_P;
#define IFX_P_DEFINED
#endif

#ifndef IFX_SCU_DEFINED
typedef struct { volatile uint32 dummy; } Ifx_SCU;
#define IFX_SCU_DEFINED
#endif

#ifndef IFX_STM_DEFINED
typedef struct { volatile uint32 dummy; } Ifx_STM;
#define IFX_STM_DEFINED
#endif

#ifndef IFX_SRC_SRCR_DEFINED
typedef struct { volatile uint32 dummy; } Ifx_SRC_SRCR;
#define IFX_SRC_SRCR_DEFINED
#endif

/* Forward declarations for nested struct pointers */
struct IfxGtm_Pwm_ChannelConfig_s;
struct IfxGtm_Pwm_OutputConfig_s;
struct IfxGtm_Pwm_DtmConfig_s;
struct IfxGtm_Pwm_InterruptConfig_s;

/* GTM CMU Clock enums (needed by IfxGtm_Pwm_ClockSource union) */
#ifndef IFXGTM_CMU_CLK_ENUM_DEFINED
typedef enum {
    IfxGtm_Cmu_Clk_0 = 0, IfxGtm_Cmu_Clk_1, IfxGtm_Cmu_Clk_2, IfxGtm_Cmu_Clk_3,
    IfxGtm_Cmu_Clk_4, IfxGtm_Cmu_Clk_5, IfxGtm_Cmu_Clk_6, IfxGtm_Cmu_Clk_7
} IfxGtm_Cmu_Clk;
#define IFXGTM_CMU_CLK_ENUM_DEFINED
#endif

#ifndef IFXGTM_CMU_FXCLK_ENUM_DEFINED
typedef enum {
    IfxGtm_Cmu_Fxclk_0 = 0, IfxGtm_Cmu_Fxclk_1, IfxGtm_Cmu_Fxclk_2,
    IfxGtm_Cmu_Fxclk_3, IfxGtm_Cmu_Fxclk_4
} IfxGtm_Cmu_Fxclk;
#define IFXGTM_CMU_FXCLK_ENUM_DEFINED
#endif

/* GTM PWM callback function pointer type */
#ifndef IFXGTM_PWM_CALLBACK_DEFINED
typedef void (*IfxGtm_Pwm_callBack)(void *data);
#define IFXGTM_PWM_CALLBACK_DEFINED
#endif

/* GTM PWM Output Configuration - for pin assignments */
#ifndef IFXGTM_PWM_OUTPUTCONFIG_DEFINED
typedef struct IfxGtm_Pwm_OutputConfig_s {
    void *pin;                    /* IfxGtm_Pwm_ToutMap* - output pin */
    void *complementaryPin;       /* IfxGtm_Pwm_ToutMap* - complementary pin for dead-time */
    uint32 polarity;              /* Ifx_ActiveState - output polarity */
    uint32 complementaryPolarity; /* Ifx_ActiveState - complementary polarity */
    uint32 outputMode;            /* IfxPort_OutputMode */
    uint32 padDriver;             /* IfxPort_PadDriver */
} IfxGtm_Pwm_OutputConfig;
#define IFXGTM_PWM_OUTPUTCONFIG_DEFINED
#endif

/* GTM PWM Dead Time - value pair */
#ifndef IFXGTM_PWM_DEADTIME_DEFINED
typedef struct { float32 rising; float32 falling; } IfxGtm_Pwm_DeadTime;
#define IFXGTM_PWM_DEADTIME_DEFINED
#endif

/* GTM PWM Dead Time Module Configuration */
#ifndef IFXGTM_PWM_DTMCONFIG_DEFINED
typedef struct IfxGtm_Pwm_DtmConfig_s {
    IfxGtm_Pwm_DeadTime deadTime;
    uint32 clockSource;
} IfxGtm_Pwm_DtmConfig;
#define IFXGTM_PWM_DTMCONFIG_DEFINED
#endif

/* GTM PWM Interrupt Configuration */
#ifndef IFXGTM_PWM_INTERRUPTCONFIG_DEFINED
typedef struct IfxGtm_Pwm_InterruptConfig_s {
    uint32 mode;                   /* IfxGtm_IrqMode */
    uint32 isrProvider;            /* IfxSrc_Tos */
    uint32 priority;               /* Ifx_Priority */
    IfxGtm_Pwm_callBack periodEvent; /* Period interrupt callback */
    IfxGtm_Pwm_callBack dutyEvent;   /* Duty interrupt callback */
} IfxGtm_Pwm_InterruptConfig;
#define IFXGTM_PWM_INTERRUPTCONFIG_DEFINED
#endif

/* GTM PWM Clock Source - union for TOM/ATOM clock */
#ifndef IFXGTM_PWM_CLOCKSOURCE_DEFINED
typedef union {
    IfxGtm_Cmu_Clk   atom;        /* Clock source for ATOM channels */
    IfxGtm_Cmu_Fxclk tom;         /* Clock source for TOM channels */
} IfxGtm_Pwm_ClockSource;
#define IFXGTM_PWM_CLOCKSOURCE_DEFINED
#endif

/* GTM PWM Channel Configuration - per-channel settings */
#ifndef IFXGTM_PWM_CHANNELCONFIG_DEFINED
typedef struct IfxGtm_Pwm_ChannelConfig_s {
    uint32 timerCh;                           /* IfxGtm_Pwm_SubModule_Ch - channel index */
    float32 phase;                            /* Phase offset in radians */
    float32 duty;                             /* Duty cycle in % (0.0 .. 100.0) */
    IfxGtm_Pwm_DtmConfig *dtm;               /* Dead time config */
    IfxGtm_Pwm_OutputConfig *output;          /* Pin connections and polarities */
    void *mscOut;                             /* MSC output config (optional) */
    IfxGtm_Pwm_InterruptConfig *interrupt;    /* Interrupt config (optional) */
} IfxGtm_Pwm_ChannelConfig;
#define IFXGTM_PWM_CHANNELCONFIG_DEFINED
#endif

/* GTM PWM Master Configuration - overall PWM settings */
#ifndef IFXGTM_PWM_CONFIG_DEFINED
typedef struct {
    Ifx_GTM *gtmSFR;                          /* Pointer to GTM module */
    uint32 cluster;                            /* IfxGtm_Cluster */
    uint32 subModule;                          /* IfxGtm_Pwm_SubModule (TOM/ATOM) */
    uint32 alignment;                          /* IfxGtm_Pwm_Alignment (center/edge) */
    uint8 numChannels;                         /* Number of channels */
    IfxGtm_Pwm_ChannelConfig *channels;        /* Channel configuration array */
    float32 frequency;                         /* PWM frequency in Hz */
    IfxGtm_Pwm_ClockSource clockSource;        /* Clock source (union: .tom / .atom) */
    uint32 dtmClockSource;                     /* IfxGtm_Dtm_ClockSource */
    boolean syncUpdateEnabled;                 /* Enable sync updates */
    boolean syncStart;                         /* Synchronized start */
} IfxGtm_Pwm_Config;
#define IFXGTM_PWM_CONFIG_DEFINED
#endif

/* GTM PWM Driver Handle */
#ifndef IFXGTM_PWM_DEFINED
typedef struct {
    Ifx_GTM *gtm;
    uint32 cluster;
    uint32 subModule;
    boolean enabled;
} IfxGtm_Pwm;
#define IFXGTM_PWM_DEFINED
#endif

/* GTM PWM Channel Handle */
#ifndef IFXGTM_PWM_CHANNEL_DEFINED
typedef struct {
    void *pwm;                     /* Parent IfxGtm_Pwm* */
    uint32 channelIndex;
    float32 duty;
} IfxGtm_Pwm_Channel;
#define IFXGTM_PWM_CHANNEL_DEFINED
#endif

/* GTM TOM driver stub types */
#ifndef IFXGTM_TOM_TOUTMAP_DEFINED
typedef struct { uint32 dummy; } IfxGtm_Tom_ToutMap;
#define IFXGTM_TOM_TOUTMAP_DEFINED
#endif

#ifndef IFXGTM_TOM_CH_DEFINED
typedef struct { uint32 dummy; } IfxGtm_Tom_Ch;
#define IFXGTM_TOM_CH_DEFINED
#endif

#ifndef IFXGTM_TOM_DEFINED
typedef struct { uint32 dummy; } IfxGtm_Tom;
#define IFXGTM_TOM_DEFINED
#endif

#ifndef IFXGTM_PWM_TOUTMAP_DEFINED
typedef struct { uint32 dummy; } IfxGtm_Pwm_ToutMap;
#define IFXGTM_PWM_TOUTMAP_DEFINED
#endif

/* Common enums for GTM PWM - use #ifndef to avoid conflicts with real iLLD */
#ifndef IFXGTM_CLUSTER_DEFINED
typedef enum { IfxGtm_Cluster_0 = 0, IfxGtm_Cluster_1, IfxGtm_Cluster_2 } IfxGtm_Cluster;
#define IFXGTM_CLUSTER_DEFINED
#endif

#ifndef IFXGTM_PWM_SUBMODULE_DEFINED
typedef enum { IfxGtm_Pwm_SubModule_tom = 0, IfxGtm_Pwm_SubModule_atom } IfxGtm_Pwm_SubModule;
#define IFXGTM_PWM_SUBMODULE_DEFINED
#endif

#ifndef IFXGTM_PWM_ALIGNMENT_DEFINED
typedef enum { IfxGtm_Pwm_Alignment_edge = 0, IfxGtm_Pwm_Alignment_center } IfxGtm_Pwm_Alignment;
#define IFXGTM_PWM_ALIGNMENT_DEFINED
#endif

#ifndef IFXGTM_PWM_SUBMODULE_CH_DEFINED
typedef enum { 
    IfxGtm_Pwm_SubModule_Ch_0 = 0, IfxGtm_Pwm_SubModule_Ch_1, IfxGtm_Pwm_SubModule_Ch_2,
    IfxGtm_Pwm_SubModule_Ch_3, IfxGtm_Pwm_SubModule_Ch_4, IfxGtm_Pwm_SubModule_Ch_5,
    IfxGtm_Pwm_SubModule_Ch_6, IfxGtm_Pwm_SubModule_Ch_7 
} IfxGtm_Pwm_SubModule_Ch;
#define IFXGTM_PWM_SUBMODULE_CH_DEFINED
#endif

#ifndef IFXGTM_DTM_CLOCKSOURCE_DEFINED
typedef enum { IfxGtm_Dtm_ClockSource_cmuClock0 = 0, IfxGtm_Dtm_ClockSource_cmuClock1 } IfxGtm_Dtm_ClockSource;
#define IFXGTM_DTM_CLOCKSOURCE_DEFINED
#endif

/* ============================================================ */
/* EGTM (TC4xx) DRIVER TYPES - TC4xx USES EGTM INSTEAD OF GTM  */
/* These are EQUIVALENT types for TC4xx family migration        */
/* ============================================================ */

/* EGTM Module stub type */
#ifndef IFX_EGTM_DEFINED
typedef struct { volatile uint32 dummy; } Ifx_EGTM;
#define IFX_EGTM_DEFINED
#endif

/* EGTM Cluster enum */
#ifndef IFXEGTM_CLUSTER_DEFINED
typedef enum { IfxEgtm_Cluster_0 = 0, IfxEgtm_Cluster_1, IfxEgtm_Cluster_2 } IfxEgtm_Cluster;
#define IFXEGTM_CLUSTER_DEFINED
#endif

/* EGTM CMU Clock types */
#ifndef IFXEGTM_CMU_CLK_DEFINED
typedef enum { 
    IfxEgtm_Cmu_Clk_0 = 0, IfxEgtm_Cmu_Clk_1, IfxEgtm_Cmu_Clk_2, IfxEgtm_Cmu_Clk_3,
    IfxEgtm_Cmu_Clk_4, IfxEgtm_Cmu_Clk_5, IfxEgtm_Cmu_Clk_6, IfxEgtm_Cmu_Clk_7 
} IfxEgtm_Cmu_Clk;
#define IFXEGTM_CMU_CLK_DEFINED
#endif

#ifndef IFXEGTM_CMU_FXCLK_DEFINED
typedef enum { IfxEgtm_Cmu_Fxclk_0 = 0, IfxEgtm_Cmu_Fxclk_1, IfxEgtm_Cmu_Fxclk_2, IfxEgtm_Cmu_Fxclk_3, IfxEgtm_Cmu_Fxclk_4 } IfxEgtm_Cmu_Fxclk;
#define IFXEGTM_CMU_FXCLK_DEFINED
#endif

/* EGTM DTM Clock Source */
#ifndef IFXEGTM_DTM_CLOCKSOURCE_DEFINED
typedef enum { IfxEgtm_Dtm_ClockSource_cmuClock0 = 0, IfxEgtm_Dtm_ClockSource_cmuClock1 } IfxEgtm_Dtm_ClockSource;
#define IFXEGTM_DTM_CLOCKSOURCE_DEFINED
#endif

/* EGTM TOM/ATOM types (TC4xx TOM and ATOM channels) */
#ifndef IFXEGTM_TOM_DEFINED
typedef enum { IfxEgtm_Tom_0 = 0, IfxEgtm_Tom_1, IfxEgtm_Tom_2 } IfxEgtm_Tom;
#define IFXEGTM_TOM_DEFINED
#endif

#ifndef IFXEGTM_TOM_CH_DEFINED
typedef enum { 
    IfxEgtm_Tom_Ch_0 = 0, IfxEgtm_Tom_Ch_1, IfxEgtm_Tom_Ch_2, IfxEgtm_Tom_Ch_3,
    IfxEgtm_Tom_Ch_4, IfxEgtm_Tom_Ch_5, IfxEgtm_Tom_Ch_6, IfxEgtm_Tom_Ch_7,
    IfxEgtm_Tom_Ch_8, IfxEgtm_Tom_Ch_9, IfxEgtm_Tom_Ch_10, IfxEgtm_Tom_Ch_11,
    IfxEgtm_Tom_Ch_12, IfxEgtm_Tom_Ch_13, IfxEgtm_Tom_Ch_14, IfxEgtm_Tom_Ch_15 
} IfxEgtm_Tom_Ch;
#define IFXEGTM_TOM_CH_DEFINED
#endif

#ifndef IFXEGTM_ATOM_DEFINED
typedef enum { IfxEgtm_Atom_0 = 0, IfxEgtm_Atom_1, IfxEgtm_Atom_2 } IfxEgtm_Atom;
#define IFXEGTM_ATOM_DEFINED
#endif

#ifndef IFXEGTM_ATOM_CH_DEFINED
typedef enum { 
    IfxEgtm_Atom_Ch_0 = 0, IfxEgtm_Atom_Ch_1, IfxEgtm_Atom_Ch_2, IfxEgtm_Atom_Ch_3,
    IfxEgtm_Atom_Ch_4, IfxEgtm_Atom_Ch_5, IfxEgtm_Atom_Ch_6, IfxEgtm_Atom_Ch_7 
} IfxEgtm_Atom_Ch;
#define IFXEGTM_ATOM_CH_DEFINED
#endif

/* EGTM ToutMap types - FORWARD DECLARATIONS ONLY */
/* Full definitions are provided in EGTM TYPES section below */
/* DO NOT define here - just declare that they will exist */
struct IfxEgtm_Tom_ToutMap_fwd;
struct IfxEgtm_Atom_ToutMap_fwd;

/* EGTM PWM types - unified PWM driver for TC4xx */
#ifndef IFXEGTM_PWM_SUBMODULE_DEFINED
typedef enum { IfxEgtm_Pwm_SubModule_tom = 0, IfxEgtm_Pwm_SubModule_atom } IfxEgtm_Pwm_SubModule;
#define IFXEGTM_PWM_SUBMODULE_DEFINED
#endif

#ifndef IFXEGTM_PWM_ALIGNMENT_DEFINED
typedef enum { IfxEgtm_Pwm_Alignment_edge = 0, IfxEgtm_Pwm_Alignment_center } IfxEgtm_Pwm_Alignment;
#define IFXEGTM_PWM_ALIGNMENT_DEFINED
#endif

#ifndef IFXEGTM_PWM_SUBMODULE_CH_DEFINED
typedef enum { 
    IfxEgtm_Pwm_SubModule_Ch_0 = 0, IfxEgtm_Pwm_SubModule_Ch_1, IfxEgtm_Pwm_SubModule_Ch_2,
    IfxEgtm_Pwm_SubModule_Ch_3, IfxEgtm_Pwm_SubModule_Ch_4, IfxEgtm_Pwm_SubModule_Ch_5,
    IfxEgtm_Pwm_SubModule_Ch_6, IfxEgtm_Pwm_SubModule_Ch_7 
} IfxEgtm_Pwm_SubModule_Ch;
#define IFXEGTM_PWM_SUBMODULE_CH_DEFINED
#endif

#ifndef IFXEGTM_IRQMODE_DEFINED
typedef enum { IfxEgtm_IrqMode_level = 0, IfxEgtm_IrqMode_pulse, IfxEgtm_IrqMode_pulseNotify, IfxEgtm_IrqMode_singlePulse } IfxEgtm_IrqMode;
#define IFXEGTM_IRQMODE_DEFINED
#endif

/* NOTE: IfxEgtm_Pwm_ToutMap, IfxEgtm_Pwm_OutputConfig are defined in EGTM TYPES section below */
/* DO NOT define minimal stubs here - use comprehensive types only */

/* ============================================================ */
/* NOTE: ALL EGTM PWM TYPES ARE DEFINED IN THE COMPREHENSIVE    */
/* "EGTM TYPES (Enhanced GTM for TC4xx)" SECTION BELOW.         */
/* DO NOT ADD MINIMAL STUBS HERE - THEY CAUSE TYPE CONFLICTS!   */
/* The following types are defined below:                       */
/*   - IfxEgtm_Pwm_DeadTime                                     */
/*   - IfxEgtm_Pwm_DtmConfig                                    */
/*   - IfxEgtm_Pwm_OutputConfig                                 */
/*   - IfxEgtm_Pwm_InterruptConfig                              */
/*   - IfxEgtm_Pwm_ChannelConfig                                */
/*   - IfxEgtm_Pwm_ClockSource                                  */
/*   - IfxEgtm_Pwm_Config                                       */
/*   - IfxEgtm_Pwm                                              */
/*   - IfxEgtm_Pwm_Channel                                      */
/*   - IfxEgtm_Tom_ToutMap, IfxEgtm_Atom_ToutMap                */
/*   - IfxEgtm_Pwm_ToutMap                                      */
/* ============================================================ */

/* EGTM PWM Driver typedef for backward compatibility */
/* NOTE: IfxEgtm_Pwm and IfxEgtm_Pwm_Driver are the same type */

/* NOTE: IfxEgtm_Pwm_Channel is defined in comprehensive EGTM TYPES section below */

/* MODULE_EGTM declaration for TC4xx */
#ifndef MODULE_EGTM
extern Ifx_EGTM MODULE_EGTM_instance;
#define MODULE_EGTM MODULE_EGTM_instance
#endif

/* EGTM P03 port for TC4D7 LED */
#ifndef MODULE_P03
extern Ifx_P MODULE_P03_instance;
#define MODULE_P03 MODULE_P03_instance
#endif

/* NOTE: Ifx_ActiveState is ALREADY defined in real iLLD Ifx_Types.h - DO NOT redefine! */

/* NULL_PTR definition for iLLD compatibility */
#ifndef NULL_PTR
#define NULL_PTR ((void*)0)
#endif

/* Port stub types - use #ifndef guards */
#ifndef IFXPORT_MODE_DEFINED
typedef enum {
    IfxPort_Mode_inputNoPullDevice = 0,
    IfxPort_Mode_inputPullDown = 1,
    IfxPort_Mode_inputPullUp = 2,
    IfxPort_Mode_outputPushPullGeneral = 16,
    IfxPort_Mode_outputPushPullAlt1 = 17,
    IfxPort_Mode_outputPushPullAlt2 = 18,
    IfxPort_Mode_outputPushPullAlt3 = 19,
    IfxPort_Mode_outputPushPullAlt4 = 20,
    IfxPort_Mode_outputPushPullAlt5 = 21,
    IfxPort_Mode_outputPushPullAlt6 = 22,
    IfxPort_Mode_outputPushPullAlt7 = 23,
    IfxPort_Mode_outputOpenDrainGeneral = 24,
    IfxPort_Mode_outputOpenDrainAlt1 = 25
} IfxPort_Mode;
#define IFXPORT_MODE_DEFINED
#endif

#ifndef IFXPORT_OUTPUTMODE_DEFINED
typedef enum {
    IfxPort_OutputMode_pushPull = 0,
    IfxPort_OutputMode_openDrain = 1
} IfxPort_OutputMode;
#define IFXPORT_OUTPUTMODE_DEFINED
#endif

#ifndef IFXPORT_PADDRIVER_DEFINED
typedef enum {
    IfxPort_PadDriver_cmosAutomotiveSpeed1 = 0,
    IfxPort_PadDriver_cmosAutomotiveSpeed2 = 1,
    IfxPort_PadDriver_cmosAutomotiveSpeed3 = 2,
    IfxPort_PadDriver_cmosAutomotiveSpeed4 = 3,
    IfxPort_PadDriver_ttlSpeed1 = 8,
    IfxPort_PadDriver_ttlSpeed2 = 9,
    IfxPort_PadDriver_ttlSpeed3 = 10,
    IfxPort_PadDriver_ttlSpeed4 = 11
} IfxPort_PadDriver;
#define IFXPORT_PADDRIVER_DEFINED
#endif

#ifndef IFXPORT_INPUTMODE_DEFINED
typedef enum {
    IfxPort_InputMode_noPullDevice = 0,
    IfxPort_InputMode_pullDown = 1,
    IfxPort_InputMode_pullUp = 2
} IfxPort_InputMode;
#define IFXPORT_INPUTMODE_DEFINED
#endif

#ifndef IFXPORT_OUTPUTIDX_DEFINED
typedef enum {
    IfxPort_OutputIdx_general = 0,
    IfxPort_OutputIdx_alt1 = 1,
    IfxPort_OutputIdx_alt2 = 2,
    IfxPort_OutputIdx_alt3 = 3,
    IfxPort_OutputIdx_alt4 = 4,
    IfxPort_OutputIdx_alt5 = 5,
    IfxPort_OutputIdx_alt6 = 6,
    IfxPort_OutputIdx_alt7 = 7
} IfxPort_OutputIdx;
#define IFXPORT_OUTPUTIDX_DEFINED
#endif

/* CPU stub types - IfxCpu_syncEvent is a simple typedef, not volatile/static */
#ifndef IFXCPU_SYNCEVENT_DEFINED
typedef uint32 IfxCpu_syncEvent;
#define IFXCPU_SYNCEVENT_DEFINED
#endif

/* NOTE: IfxCpu_Id is an enum in real iLLD - check before defining */
#ifndef IFXCPU_ID_DEFINED
typedef enum { IfxCpu_Id_0 = 0, IfxCpu_Id_1, IfxCpu_Id_2, IfxCpu_Id_none = 15 } IfxCpu_Id;
#define IFXCPU_ID_DEFINED
#endif

/* ===== MODULE_* INSTANCE DECLARATIONS FOR TDD ===== */
/* These allow production code to compile referencing hardware modules.
   The actual instances are defined in ifx_types.c */

/* Module instance extern declarations */
#ifndef MODULE_GTM
extern Ifx_GTM MODULE_GTM_instance;
#define MODULE_GTM MODULE_GTM_instance
#endif

#ifndef MODULE_SCU
extern Ifx_SCU MODULE_SCU_instance;
#define MODULE_SCU MODULE_SCU_instance
#endif

#ifndef MODULE_STM0
extern Ifx_STM MODULE_STM0_instance;
#define MODULE_STM0 MODULE_STM0_instance
#endif
#ifndef MODULE_STM1
extern Ifx_STM MODULE_STM1_instance;
#define MODULE_STM1 MODULE_STM1_instance
#endif
#ifndef MODULE_STM2
extern Ifx_STM MODULE_STM2_instance;
#define MODULE_STM2 MODULE_STM2_instance
#endif

#ifndef MODULE_P00
extern Ifx_P MODULE_P00_instance;
#define MODULE_P00 MODULE_P00_instance
#endif
#ifndef MODULE_P01
extern Ifx_P MODULE_P01_instance;
#define MODULE_P01 MODULE_P01_instance
#endif
#ifndef MODULE_P02
extern Ifx_P MODULE_P02_instance;
#define MODULE_P02 MODULE_P02_instance
#endif
#ifndef MODULE_P03
extern Ifx_P MODULE_P03_instance;
#define MODULE_P03 MODULE_P03_instance
#endif
#ifndef MODULE_P04
extern Ifx_P MODULE_P04_instance;
#define MODULE_P04 MODULE_P04_instance
#endif
#ifndef MODULE_P05
extern Ifx_P MODULE_P05_instance;
#define MODULE_P05 MODULE_P05_instance
#endif
#ifndef MODULE_P06
extern Ifx_P MODULE_P06_instance;
#define MODULE_P06 MODULE_P06_instance
#endif
#ifndef MODULE_P10
extern Ifx_P MODULE_P10_instance;
#define MODULE_P10 MODULE_P10_instance
#endif
#ifndef MODULE_P11
extern Ifx_P MODULE_P11_instance;
#define MODULE_P11 MODULE_P11_instance
#endif
#ifndef MODULE_P13
extern Ifx_P MODULE_P13_instance;
#define MODULE_P13 MODULE_P13_instance
#endif
#ifndef MODULE_P14
extern Ifx_P MODULE_P14_instance;
#define MODULE_P14 MODULE_P14_instance
#endif
#ifndef MODULE_P15
extern Ifx_P MODULE_P15_instance;
#define MODULE_P15 MODULE_P15_instance
#endif
#ifndef MODULE_P20
extern Ifx_P MODULE_P20_instance;
#define MODULE_P20 MODULE_P20_instance
#endif
#ifndef MODULE_P21
extern Ifx_P MODULE_P21_instance;
#define MODULE_P21 MODULE_P21_instance
#endif
#ifndef MODULE_P22
extern Ifx_P MODULE_P22_instance;
#define MODULE_P22 MODULE_P22_instance
#endif
#ifndef MODULE_P23
extern Ifx_P MODULE_P23_instance;
#define MODULE_P23 MODULE_P23_instance
#endif
#ifndef MODULE_P32
extern Ifx_P MODULE_P32_instance;
#define MODULE_P32 MODULE_P32_instance
#endif
#ifndef MODULE_P33
extern Ifx_P MODULE_P33_instance;
#define MODULE_P33 MODULE_P33_instance
#endif
#ifndef MODULE_P34
extern Ifx_P MODULE_P34_instance;
#define MODULE_P34 MODULE_P34_instance
#endif


#endif /* IFX_TYPES_H */
