/* AUTOGENERATED MOCK — IfxEgtm_Trigger.h (TC4xx) */
#ifndef IFXEGTM_TRIGGER_H
#define IFXEGTM_TRIGGER_H
#include "mock_egtm_atom_3_phase_inverter_pwm.h"
#include "IfxEgtm.h"

boolean IfxEgtm_Trigger_trigToAdc(IfxEgtm_Cluster egtmCluster, IfxEgtm_TrigSource egtmSource, IfxEgtm_TrigChannel Channel, IfxEgtm_Cfg_AdcTriggerSignal adcTrigSignal);

#endif /* IFXEGTM_TRIGGER_H */
