/* AUTOGENERATED MOCK — IfxPort.h (TC4xx) */
#ifndef IFXPORT_H
#define IFXPORT_H
#include "mock_egtm_atom_3_phase_inverter_pwm.h"

typedef enum {
    IfxPort_OutputMode_pushPull  = ((0U << 1U) | 1U),
    IfxPort_OutputMode_openDrain = ((1U << 1U) | 1U)
} IfxPort_OutputMode;

typedef enum {
    IfxPort_OutputIdx_general = ((0U << 4U) | 1U),
    IfxPort_OutputIdx_alt1    = ((1U << 4U) | 1U),
    IfxPort_OutputIdx_alt2    = ((2U << 4U) | 1U),
    IfxPort_OutputIdx_alt3    = ((3U << 4U) | 1U),
    IfxPort_OutputIdx_alt4    = ((4U << 4U) | 1U),
    IfxPort_OutputIdx_alt5    = ((5U << 4U) | 1U),
    IfxPort_OutputIdx_alt6    = ((6U << 4U) | 1U),
    IfxPort_OutputIdx_alt7    = ((7U << 4U) | 1U),
    IfxPort_OutputIdx_alt8    = ((8U << 4U) | 1U),
    IfxPort_OutputIdx_alt9    = ((9U << 4U) | 1U),
    IfxPort_OutputIdx_alt10   = ((10U << 4U) | 1U),
    IfxPort_OutputIdx_alt11   = ((11U << 4U) | 1U),
    IfxPort_OutputIdx_alt12   = ((12U << 4U) | 1U),
    IfxPort_OutputIdx_alt13   = ((13U << 4U) | 1U),
    IfxPort_OutputIdx_alt14   = ((14U << 4U) | 1U),
    IfxPort_OutputIdx_alt15   = ((15U << 4U) | 1U)
} IfxPort_OutputIdx;

typedef enum {
    IfxPort_PadDriver_cmosAutomotiveSpeed1 = (0 << 3) | (0 << 0),
    IfxPort_PadDriver_cmosAutomotiveSpeed2 = (0 << 3) | (1 << 0),
    IfxPort_PadDriver_cmosAutomotiveSpeed3 = (0 << 3) | (2 << 0),
    IfxPort_PadDriver_ttlSpeed1            = (2 << 3) | (0 << 0),
    IfxPort_PadDriver_ttlSpeed2            = (2 << 3) | (1 << 0),
    IfxPort_PadDriver_ttlSpeed3            = (2 << 3) | (2 << 0),
    IfxPort_PadDriver_ttl3v3Speed1         = (3 << 3) | (0 << 0),
    IfxPort_PadDriver_ttl3v3Speed2         = (3 << 3) | (1 << 0),
    IfxPort_PadDriver_ttl3v3Speed3         = (3 << 3) | (2 << 0)
} IfxPort_PadDriver;

typedef struct { Ifx_P *port; uint8 pinIndex; } IfxPort_Pin;

typedef struct {
    Ifx_P            *port;
    uint8             pinIndex;
    IfxPort_OutputIdx mode;
    IfxPort_PadDriver padDriver;
} IfxPort_Pin_Config;

/* Required functions for this module */
void IfxPort_togglePin(Ifx_P *port, uint8 pinIndex);
void IfxPort_setPinModeOutput(Ifx_P *port, uint8 pinIndex, IfxPort_OutputMode mode, IfxPort_OutputIdx index);

#endif /* IFXPORT_H */
