/* AUTOGENERATED UNITY TESTS FOR GTM_TOM_3_PHASE_INVERTER_PWM */

#include "unity.h"
#include "mock_gtm_tom_3_phase_inverter_pwm.h"
#include "gtm_tom_3_phase_inverter_pwm.h"

/* UT macros matching configuration values */
#define UT_FLOAT_EPSILON               (1e-4f)
#define UT_INIT_DUTY_U_PERCENT        (25.0f)
#define UT_INIT_DUTY_V_PERCENT        (50.0f)
#define UT_INIT_DUTY_W_PERCENT        (75.0f)
#define UT_STEP_PERCENT               (10.0f)
#define UT_PWM_FREQ_HZ                (20000.0f)
#define UT_NUM_CHANNELS               (3u)

/* Production functions may be static in the .c; tests call them via extern declarations
   as required by the test harness rules. */
extern void configurePwmChannels(uint8_t channelCount);
extern void updateGtmTom3phInvDuty(void);

void setUp(void) {
    mock_gtm_tom_3_phase_inverter_pwm_reset();
}

void tearDown(void) {}

/* Group 1 - configurePwmChannels: initialization / enable guard */

void test_TC1_001_init_when_gtm_disabled_calls_enable_and_clocks(void)
{
    /* Arrange: peripheral appears disabled so driver must enable and configure CMU */
    mock_IfxGtm_isEnabled_returnValue = 0; /* false */

    /* Act */
    configurePwmChannels((uint8_t)UT_NUM_CHANNELS);

    /* Assert: initConfig and init called exactly once */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Pwm_initConfig_getCallCount(), "IfxGtm_Pwm_initConfig should be called once during init sequence");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Pwm_init_getCallCount(), "IfxGtm_Pwm_init should be called once during init sequence");

    /* Assert: enable & CMU calls invoked when GTM initially disabled */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_isEnabled_getCallCount(), "IfxGtm_isEnabled should be called once to check GTM state");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_enable_getCallCount(), "IfxGtm_enable should be called when GTM is disabled");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Cmu_getModuleFrequency_getCallCount(), "IfxGtm_Cmu_getModuleFrequency should be called when enabling GTM");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Cmu_setGclkFrequency_getCallCount(), "IfxGtm_Cmu_setGclkFrequency should be called when configuring CMU");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Cmu_setClkFrequency_getCallCount(), "IfxGtm_Cmu_setClkFrequency should be called when configuring CMU");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Cmu_enableClocks_getCallCount(), "IfxGtm_Cmu_enableClocks should be called when configuring CMU");

    /* Assert: initial runtime duty update and LED pin configuration performed */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_getCallCount(), "Initial duty update should be called once after PWM init");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxPort_setPinModeOutput_getCallCount(), "LED pin(s) should be configured as output after init");

    /* Assert: init() spy shows the correct PWM configuration values (user-set values asserted on init spy per rules) */
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, UT_PWM_FREQ_HZ, mock_IfxGtm_Pwm_init_lastFrequency, "IfxGtm_Pwm_init should be called with the configured PWM frequency");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE((uint32_t)UT_NUM_CHANNELS, (uint32_t)mock_IfxGtm_Pwm_init_lastNumChannels, "IfxGtm_Pwm_init should be called with the correct number of logical channels");
}

void test_TC1_002_init_when_gtm_already_enabled_skips_enable_and_clocks(void)
{
    /* Arrange: peripheral already enabled */
    mock_IfxGtm_isEnabled_returnValue = 1; /* true */

    /* Act */
    configurePwmChannels((uint8_t)UT_NUM_CHANNELS);

    /* Assert: initConfig and init still called once */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Pwm_initConfig_getCallCount(), "IfxGtm_Pwm_initConfig should be called once even when GTM is enabled");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Pwm_init_getCallCount(), "IfxGtm_Pwm_init should be called once during init sequence");

    /* Assert: enable/CMU should NOT be called because GTM was already enabled */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_isEnabled_getCallCount(), "IfxGtm_isEnabled should be called once to check GTM state");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(0u, mock_IfxGtm_enable_getCallCount(), "IfxGtm_enable should NOT be called when GTM is already enabled");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(0u, mock_IfxGtm_Cmu_getModuleFrequency_getCallCount(), "IfxGtm_Cmu_getModuleFrequency should NOT be called when GTM is already enabled");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(0u, mock_IfxGtm_Cmu_setGclkFrequency_getCallCount(), "IfxGtm_Cmu_setGclkFrequency should NOT be called when GTM is already enabled");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(0u, mock_IfxGtm_Cmu_setClkFrequency_getCallCount(), "IfxGtm_Cmu_setClkFrequency should NOT be called when GTM is already enabled");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(0u, mock_IfxGtm_Cmu_enableClocks_getCallCount(), "IfxGtm_Cmu_enableClocks should NOT be called when GTM is already enabled");

    /* Assert: initial runtime update and LED configuration still occur */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_getCallCount(), "Initial duty update should be called once after PWM init");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxPort_setPinModeOutput_getCallCount(), "LED pin(s) should be configured as output after init");
}

/* Group 2 - configurePwmChannels: configuration values */

void test_TC2_001_initial_duties_are_stored_and_passed_to_hal(void)
{
    /* Arrange */
    mock_IfxGtm_isEnabled_returnValue = 1; /* assume GTM already enabled for simplicity */

    /* Act */
    configurePwmChannels((uint8_t)UT_NUM_CHANNELS);

    /* Assert: the driver update was called once and the last duties reflect the configured initial percentages */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_getCallCount(), "Initial duty update should be called once");
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, UT_INIT_DUTY_U_PERCENT, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_lastDuties[0], "Initial U duty should be 25% and passed to HAL as percent");
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, UT_INIT_DUTY_V_PERCENT, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_lastDuties[1], "Initial V duty should be 50% and passed to HAL as percent");
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, UT_INIT_DUTY_W_PERCENT, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_lastDuties[2], "Initial W duty should be 75% and passed to HAL as percent");

    /* Assert: correct number of channels captured by init spy */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE((uint32_t)UT_NUM_CHANNELS, (uint32_t)mock_IfxGtm_Pwm_init_lastNumChannels, "IfxGtm_Pwm_init should be called with 3 logical channels for 3-phase PWM");
}

void test_TC2_002_init_frequency_matches_pwm_requirement_and_initConfig_called_first(void)
{
    /* Arrange */
    mock_IfxGtm_isEnabled_returnValue = 1;

    /* Act */
    configurePwmChannels((uint8_t)UT_NUM_CHANNELS);

    /* Assert: initConfig was called (SDK defaults were populated) and init called (application values captured)
       Per rules: application-set frequency must be asserted on init spy (not initConfig spy) */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Pwm_initConfig_getCallCount(), "IfxGtm_Pwm_initConfig should be called to populate defaults before application sets fields");
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(1u, mock_IfxGtm_Pwm_init_getCallCount(), "IfxGtm_Pwm_init should be called to apply configured values");

    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, UT_PWM_FREQ_HZ, mock_IfxGtm_Pwm_init_lastFrequency, "IfxGtm_Pwm_init should be called with user-configured PWM frequency (20 kHz)");
}

/* Group 3 - configurePwmChannels: runtime update logic */

void test_TC3_001_single_update_increments_each_channel_and_calls_hal_once_per_update(void)
{
    /* Arrange: initialize module state first */
    mock_IfxGtm_isEnabled_returnValue = 1;
    configurePwmChannels((uint8_t)UT_NUM_CHANNELS);

    uint32_t before = mock_IfxGtm_Pwm_updateChannelsDutyImmediate_getCallCount();

    /* Act: perform one runtime update (should increment each duty by UT_STEP_PERCENT) */
    updateGtmTom3phInvDuty();

    /* Assert: HAL update called exactly once more */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(before + 1u, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_getCallCount(), "updateGtmTom3phInvDuty should call HAL update exactly once per invocation");

    /* Assert: duties incremented by UT_STEP_PERCENT */
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, UT_INIT_DUTY_U_PERCENT + UT_STEP_PERCENT, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_lastDuties[0], "U duty should increase by step percent on single update");
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, UT_INIT_DUTY_V_PERCENT + UT_STEP_PERCENT, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_lastDuties[1], "V duty should increase by step percent on single update");
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, UT_INIT_DUTY_W_PERCENT + UT_STEP_PERCENT, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_lastDuties[2], "W duty should increase by step percent on single update");
}

void test_TC3_002_multiple_updates_wraps_channel_independently_when_exceeding_100_percent(void)
{
    /* Arrange: initialize module state */
    mock_IfxGtm_isEnabled_returnValue = 1;
    configurePwmChannels((uint8_t)UT_NUM_CHANNELS);

    uint32_t before = mock_IfxGtm_Pwm_updateChannelsDutyImmediate_getCallCount();

    /* Act: call update 3 times
       Starting from [25,50,75]
       After 1: [35,60,85]
       After 2: [45,70,95]
       After 3: [55,80,  (95+10)>=100 => wrap => 10 ] => [55,80,10]
    */
    updateGtmTom3phInvDuty();
    updateGtmTom3phInvDuty();
    updateGtmTom3phInvDuty();

    /* Assert: HAL update invoked three more times */
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(before + 3u, mock_IfxGtm_Pwm_updateChannelsDutyImmediate_getCallCount(), "Three update calls should result in three HAL update invocations");

    /* Assert: resulting duties after 3 updates */
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, (UT_INIT_DUTY_U_PERCENT + 3.0f * UT_STEP_PERCENT), mock_IfxGtm_Pwm_updateChannelsDutyImmediate_lastDuties[0], "U duty should be incremented by 30% after 3 updates");
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, (UT_INIT_DUTY_V_PERCENT + 3.0f * UT_STEP_PERCENT), mock_IfxGtm_Pwm_updateChannelsDutyImmediate_lastDuties[1], "V duty should be incremented by 30% after 3 updates");
    /* W wraps: expected final is 10% per wrap semantics described in requirements */
    TEST_ASSERT_FLOAT_WITHIN_MESSAGE(UT_FLOAT_EPSILON, (UT_STEP_PERCENT), mock_IfxGtm_Pwm_updateChannelsDutyImmediate_lastDuties[2], "W duty should wrap and equal step percent after exceeding 100% (wrap semantics)");
}

int main(void)
{
    UNITY_BEGIN();

    /* Group 1 */
    RUN_TEST(test_TC1_001_init_when_gtm_disabled_calls_enable_and_clocks);
    RUN_TEST(test_TC1_002_init_when_gtm_already_enabled_skips_enable_and_clocks);

    /* Group 2 */
    RUN_TEST(test_TC2_001_initial_duties_are_stored_and_passed_to_hal);
    RUN_TEST(test_TC2_002_init_frequency_matches_pwm_requirement_and_initConfig_called_first);

    /* Group 3 */
    RUN_TEST(test_TC3_001_single_update_increments_each_channel_and_calls_hal_once_per_update);
    RUN_TEST(test_TC3_002_multiple_updates_wraps_channel_independently_when_exceeding_100_percent);

    return UNITY_END();
}
